version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: es-1c-helper
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  mcp-server:
    build: .
    container_name: mcp-1c-helper
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./data/hbk:/app/data/hbk:ro
      - ./data/logs:/app/logs
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - LOG_LEVEL=INFO
      - HBK_FILE_PATH=/app/data/hbk/1c_documentation.hbk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  elasticsearch_data:
